### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

### ISSUE THREAD

**Issue by ulidtko** [stormherz/atom-incsearch#4]
Repro steps:

1. `apm install api-docs`
2. Open any buffer, select a keyword (e.g. `undefined`), Ctrl+Shift+P, `Api Docs: Search Under Cursor`. An HTML doc view pane opens.
3. Focus the doc pane, Ctrl+Shift+P, `incsearch:toggle`.
4. Unhandled exception.

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Ubuntu 15.10
**Thrown From**: [incsearch](https://github.com/Stormherz/atom-incsearch) package, v0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

```
At /home/ulidtko/.atom/packages/incsearch/lib/incsearch.coffee:138

TypeError: Cannot read property 'onDidDestroy' of undefined
    at Object.show (/home/ulidtko/.atom/packages/incsearch/lib/incsearch.coffee:138:11)
    at atom-workspace.subscriptions.add.atom.commands.add.incsearch:toggle (/home/ulidtko/.atom/packages/incsearch/lib/incsearch.coffee:108:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by stormherz** [comment]
@ulidtko thanks for the report, I can see the issue, which I'll fix, though I'm not quite sure what should be the expected behaviour here. Currently incsearch will support only text editors, not html panes - did you expect to toggle search field in the editor pane?

**Comment by ulidtko** [comment]
@stormherz yes, exactly I did. Is it technically challenging to implement search in html panes?

But anyway, it shouldn't crash nonetheless.

**Comment by stormherz** [comment]
@ulidtko I'll release the patch today and will look into html pane search

**Comment by ulidtko** [comment]
Good enough for me, thanks.

Html pane search would be a nice addition, since the built-in Ctrl-F search can't currently find anything in those.
